
<script type="text/javascript" src="../js/jquery.js"></script>
<?php
    	$records =  $this->methodinblock();


      	$cnt	= count($records);
   	    $url = Mage::getUrl('*/*');
        if ($_SERVER['HTTPS'] == 'on') {
              $url = str_replace('http:', 'https:', $url);
        }

         $baseurl =  Mage::helper('core/url')->getHomeUrl();//Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);

?>
<!-- start center -->
<div id="main" class="col-main">
    <!-- start global messages -->
        <?php echo $this->getChildHtml('global_messages') ?>
    <!-- end global messages -->
    <!-- start content -->
        <?php echo $this->getChildHtml('content') ?>&nbsp;
    <!-- end content -->
</div>
<!-- end center -->
    <h1><?php //echo $this->__('Product Listings') ?></h1>
    <table border="1" >
        <tbody>
            <tr>
                <td colspan="3" ></td>
               
                <td colspan="2"><a href="<?php echo $baseurl.'test/index/new'; ?>" > Add New</a></td>
            </tr>
        	<tr>
        		<td><strong>Title</strong></td>
        		<td><strong>Description</strong></td>
                <td><strong>Media</strong></td>

        		<td><strong>Edit</strong></td>
        		<td><strong>Delete<strong></td>
        	</tr>
           	<tr>
            	<?php 
            	    for ($i=1; $i < $cnt; $i++) {  
            		$cnt2 = count($records[$i]); ?>
            		<tr>
                		<?php 
                			for ($j=1; $j < $cnt2; $j++) {  ?>
                			<td>
                 	   			<?php 
                                    //$appRoot= Mage::getRoot();
                                    //$path = $appRoot.DS.'code'.DS.'local'.DS.'Excellence'.DS.'Test'.DS.'image'.DS;
                                    //$path = Mage::getBaseDir('media') . DS ;
                                   $t = Mage::getBaseUrl (); 
                                   $path = str_replace('index.php/','media/',$t);
                                    //echo $path;

                                if($j == '3')
                                { //echo $path.$records[$i]['3'];
                                    if($records[$i]['3'] != '' ) { ?>
                                    <a href="javascript:void(0);" onclick="showCompare('<?php echo $path.$records[$i]['3']; ?>')"; ><img src="<?php echo $path.$records[$i]['3']; ?>" width="50" height="40" /></a>
                                    <?php //echo $this->helper('catalog/image')->init($records[$i]['3'], 'small_image')->resize(270) ?>
                                    <?php  } else { ?>
                                    <a href="javascript:void(0);" onclick="showCompare('<?php echo $path.$records[$i]['3']; ?>')"; ><img src="<?php echo $path.'noimage.jpeg'; ?>" width="50" height="40" /></a>
                                    <?php } ?>
                                <?php }
                                else
                                {
                                    echo $records[$i][$j]; 
                                }
                            ?>
                 	   		</td>
                		<?php } 
                        ?>
                          	<td>
            					<a href="<?php echo $baseurl.'test/index/edit/id/'.$records[$i][0]; ?>" >Edit </a>
            				</td>
            				<td>
            					<a href="<?php echo $baseurl.'test/index/delete/id/'.$records[$i][0]; ?>" >Delete</a>
            				</td>
            		</tr>
            	<?php 	} ?>
        	</tr>
        </tbody>
    </table>


<script type="text/javascript">


//    $( document ).ready(function() {
//         alert("dddddddddddddddd");
// });

//<![CDATA[
function showCompare(url) {
 

    winCompare = new Window({className:'magento',title:'Compare Products',url:url,width:820,height:600,minimizable:false,maximizable:false,showEffectOptions:{duration:0.4},hideEffectOptions:{duration:0.4}});
    alert(winCompare);

    winCompare.setZIndex(100);
    winCompare.showCenter(true);
}
// ]]></script>

